[package]
name = "rust-serial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-derive = "0.3.3"
serial = "0.4.0"
num-traits = "0.2.15"
clap = "3.1.18"
hex = "0.4.3"
simple-error = "0.2.1"
