
-- generated by elm_rs


module Messages exposing (..)

import Dict exposing (Dict)
import File
import Http
import Json.Decode
import Json.Encode
import Payload exposing (AutomatoId, automatoIdDecoder, automatoIdEncoder, PayloadEnum, payloadEnumDecoder, payloadEnumEncoder)
import SerialError exposing (Error, errorDecoder, errorEncoder)
import Url.Builder


resultDecoder : Json.Decode.Decoder e -> Json.Decode.Decoder t -> Json.Decode.Decoder (Result e t)
resultDecoder errDecoder okDecoder =
    Json.Decode.oneOf
        [ Json.Decode.map Ok (Json.Decode.field "Ok" okDecoder)
        , Json.Decode.map Err (Json.Decode.field "Err" errDecoder)
        ]


resultEncoder : (e -> Json.Encode.Value) -> (t -> Json.Encode.Value) -> (Result e t -> Json.Encode.Value)
resultEncoder errEncoder okEncoder enum =
    case enum of
        Ok inner ->
            Json.Encode.object [ ( "Ok", okEncoder inner ) ]
        Err inner ->
            Json.Encode.object [ ( "Err", errEncoder inner ) ]


type ServerResponse
    = SrAutomatos (List (AutomatoId))
    | SrAutomatoMsg (AutomatoMsg)
    | SrSerialPorts (List (SerialPortInfo))
    | SrSerialError (Error)
    | SrGenericError (String)


serverResponseEncoder : ServerResponse -> Json.Encode.Value
serverResponseEncoder enum =
    case enum of
        SrAutomatos inner ->
            Json.Encode.object [ ( "SrAutomatos", Json.Encode.list (automatoIdEncoder) inner ) ]
        SrAutomatoMsg inner ->
            Json.Encode.object [ ( "SrAutomatoMsg", automatoMsgEncoder inner ) ]
        SrSerialPorts inner ->
            Json.Encode.object [ ( "SrSerialPorts", Json.Encode.list (serialPortInfoEncoder) inner ) ]
        SrSerialError inner ->
            Json.Encode.object [ ( "SrSerialError", errorEncoder inner ) ]
        SrGenericError inner ->
            Json.Encode.object [ ( "SrGenericError", Json.Encode.string inner ) ]

serverResponseDecoder : Json.Decode.Decoder ServerResponse
serverResponseDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.map SrAutomatos (Json.Decode.field "SrAutomatos" (Json.Decode.list (automatoIdDecoder)))
        , Json.Decode.map SrAutomatoMsg (Json.Decode.field "SrAutomatoMsg" (automatoMsgDecoder))
        , Json.Decode.map SrSerialPorts (Json.Decode.field "SrSerialPorts" (Json.Decode.list (serialPortInfoDecoder)))
        , Json.Decode.map SrSerialError (Json.Decode.field "SrSerialError" (errorDecoder))
        , Json.Decode.map SrGenericError (Json.Decode.field "SrGenericError" (Json.Decode.string))
        ]

type PublicMessage
    = PrGetAutomatoList
    | PrAutomatoMsg (AutomatoMsg)
    | PrGetSerialPortList


publicMessageEncoder : PublicMessage -> Json.Encode.Value
publicMessageEncoder enum =
    case enum of
        PrGetAutomatoList ->
            Json.Encode.string "PrGetAutomatoList"
        PrAutomatoMsg inner ->
            Json.Encode.object [ ( "PrAutomatoMsg", automatoMsgEncoder inner ) ]
        PrGetSerialPortList ->
            Json.Encode.string "PrGetSerialPortList"

publicMessageDecoder : Json.Decode.Decoder PublicMessage
publicMessageDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "PrGetAutomatoList" ->
                            Json.Decode.succeed PrGetAutomatoList
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map PrAutomatoMsg (Json.Decode.field "PrAutomatoMsg" (automatoMsgDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "PrGetSerialPortList" ->
                            Json.Decode.succeed PrGetSerialPortList
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]

type alias AutomatoMsg =
    { id : AutomatoId
    , message : PayloadEnum
    }


automatoMsgEncoder : AutomatoMsg -> Json.Encode.Value
automatoMsgEncoder struct =
    Json.Encode.object
        [ ( "id", (automatoIdEncoder) struct.id )
        , ( "message", (payloadEnumEncoder) struct.message )
        ]


automatoMsgDecoder : Json.Decode.Decoder AutomatoMsg
automatoMsgDecoder =
    Json.Decode.succeed AutomatoMsg
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (automatoIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "message" (payloadEnumDecoder)))


type alias WhatMsg =
    { what : String
    , msg : AutomatoMsg
    }


whatMsgEncoder : WhatMsg -> Json.Encode.Value
whatMsgEncoder struct =
    Json.Encode.object
        [ ( "what", (Json.Encode.string) struct.what )
        , ( "msg", (automatoMsgEncoder) struct.msg )
        ]


whatMsgDecoder : Json.Decode.Decoder WhatMsg
whatMsgDecoder =
    Json.Decode.succeed WhatMsg
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "what" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "msg" (automatoMsgDecoder)))


type alias WhatError =
    { what : String
    , msg : Error
    }


whatErrorEncoder : WhatError -> Json.Encode.Value
whatErrorEncoder struct =
    Json.Encode.object
        [ ( "what", (Json.Encode.string) struct.what )
        , ( "msg", (errorEncoder) struct.msg )
        ]


whatErrorDecoder : Json.Decode.Decoder WhatError
whatErrorDecoder =
    Json.Decode.succeed WhatError
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "what" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "msg" (errorDecoder)))


type alias UsbPortInfo =
    { vid : Int
    , pid : Int
    , serialNumber : Maybe (String)
    , manufacturer : Maybe (String)
    , product : Maybe (String)
    }


usbPortInfoEncoder : UsbPortInfo -> Json.Encode.Value
usbPortInfoEncoder struct =
    Json.Encode.object
        [ ( "vid", (Json.Encode.int) struct.vid )
        , ( "pid", (Json.Encode.int) struct.pid )
        , ( "serial_number", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.serialNumber )
        , ( "manufacturer", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.manufacturer )
        , ( "product", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.product )
        ]


usbPortInfoDecoder : Json.Decode.Decoder UsbPortInfo
usbPortInfoDecoder =
    Json.Decode.succeed UsbPortInfo
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "vid" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "pid" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "serial_number" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "manufacturer" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "product" (Json.Decode.nullable (Json.Decode.string))))


type SerialPortType
    = UsbPort (UsbPortInfo)
    | PciPort
    | BluetoothPort
    | Unknown


serialPortTypeEncoder : SerialPortType -> Json.Encode.Value
serialPortTypeEncoder enum =
    case enum of
        UsbPort inner ->
            Json.Encode.object [ ( "UsbPort", usbPortInfoEncoder inner ) ]
        PciPort ->
            Json.Encode.string "PciPort"
        BluetoothPort ->
            Json.Encode.string "BluetoothPort"
        Unknown ->
            Json.Encode.string "Unknown"

serialPortTypeDecoder : Json.Decode.Decoder SerialPortType
serialPortTypeDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.map UsbPort (Json.Decode.field "UsbPort" (usbPortInfoDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "PciPort" ->
                            Json.Decode.succeed PciPort
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "BluetoothPort" ->
                            Json.Decode.succeed BluetoothPort
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Unknown" ->
                            Json.Decode.succeed Unknown
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]

type alias SerialPortInfo =
    { portName : String
    , portType : SerialPortType
    }


serialPortInfoEncoder : SerialPortInfo -> Json.Encode.Value
serialPortInfoEncoder struct =
    Json.Encode.object
        [ ( "port_name", (Json.Encode.string) struct.portName )
        , ( "port_type", (serialPortTypeEncoder) struct.portType )
        ]


serialPortInfoDecoder : Json.Decode.Decoder SerialPortInfo
serialPortInfoDecoder =
    Json.Decode.succeed SerialPortInfo
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "port_name" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "port_type" (serialPortTypeDecoder)))


